# Generated by Django 4.2.7 on 2025-03-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
