# Generated by Django 4.2.7 on 2025-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_templatestatus_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='approval_status',
            field=models.CharField(default='Pending for Approval', max_length=50),
        ),
    ]
