# Generated by Django 4.2.7 on 2025-03-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_template_approval_status'),
        ('dashboard', '0006_template_approval_status'),
    ]

    operations = [
    ]
