# Generated by Django 4.2.7 on 2025-03-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_template_templatestatus'),
        ('dashboard', '0007_merge_20250312_0937'),
    ]

    operations = [
    ]
