# Generated by Django 4.2.7 on 2025-03-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_merge_20250312_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalsettings',
            name='keywords_approve',
            field=models.TextField(default='', help_text='Enter keywords separated by commas. Templates containing these words will be approved automatically.'),
        ),
        migrations.AddField(
            model_name='approvalsettings',
            name='keywords_manual',
            field=models.TextField(default='', help_text='Enter keywords separated by commas. Templates containing these words will be sent for manual approval.'),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved_system', 'Approved by System'), ('approved_admin', 'Approved by Admin')], default='pending', max_length=20),
        ),
    ]
