# Generated by Django 4.2.7 on 2025-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_approvalsettings_keywords_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='variables',
            field=models.TextField(blank=True),
        ),
    ]
